name: obrs data

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to GitHub runner
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Install the Python version needed
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . # Install dependencies based on pyproject.toml
          
      - name: Execute ORBS data processing script
        run: generate-data # Run the script using the entry point defined in pyproject.toml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated data update"
        id: auto-commit-action
